### ISSUE TITLE
why do you use Redis Pubsub

### ISSUE THREAD

**Issue by HoangNgo88** [dimmkan/Golang-redis-pubsub#1]
Hi, I am reading your project and I love this project
I have a question, why do you choose Redis Pubsub in your project instead of others like RabbitMQ or Kafka, are there any special features that others dont have it. Can you share me  it. I am wondering when I should choose Redis Pubsub instead of others like RabbitMQ or Kafka

**Comment by dimmkan** [comment]
Hi! I am very pleased that you are interested in my test project. I used Redis Pubsub in it for the reason that I don't need guaranteed delivery, which is available from RabbitMQ or Kafka. At the same time, I still need the ability to connect multiple consumers to the same channel. Therefore, my choice settled on Rays Pubsub. Thus, the answer to your question looks like this - if you need guarantees of delivery to a certain number of consumers, use RabbitMQ or Kafka. If you need a simple round-robin for a certain number of consumers without guaranteed delivery, use Redis Pubsub. I hope I answered your question and this answer was useful))
